---
- name: Install NGINX
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy NGINX configuration for Flask and Web Server
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/sites-available/flask_nginx.conf

- name: Enable NGINX site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/flask_nginx.conf
    dest: /etc/nginx/sites-enabled/flask_nginx.conf
    state: link

- name: Remove default NGINX site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart NGINX
  ansible.builtin.systemd:
    name: nginx
    state: restarted