---
- name: Install Flask and Gunicorn
  ansible.builtin.pip:
    name: "{{ package_list }}"
    executable: pip3

- name: Create Flask app directory
  ansible.builtin.file:
    path: /var/www/flask_app
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Generate a random string for JWT encoding
  set_fact:
    random_string: "{{ lookup('password', '/dev/null', length=20) }}"

- name: Save random string for JWT encoding to repo
  ansible.builtin.copy:
    content: "{{ random_string }}"
    dest: /var/www/flask_app/secret.txt
    owner: root
    group: root
    mode: '0644'

- name: Copy the flask app to /var/www/flask_app
  ansible.builtin.copy:
    src: app.py
    dest: /var/www/flask_app/app.py

- name: Replace localhost with the specific IP in MongoClient connection string
  ansible.builtin.replace:
    path: /var/www/flask_app/app.py
    regexp: 'MongoClient\("mongodb://localhost:27017/"\)'
    replace: 'MongoClient("mongodb://{{ mongo_local_ip }}:27017/")'

- name: Create Gunicorn systemd service for Flask
  ansible.builtin.copy:
    src: gunicorn.conf
    dest: /etc/systemd/system/gunicorn.service

- name: Start and enable Gunicorn service
  ansible.builtin.systemd:
    name: gunicorn
    state: started
    enabled: yes